### ISSUE TITLE
Teams presense stopped working

### ISSUE THREAD

**Issue by maxweisspoker** [a1comms/chromeos-apps-for-office365#4]
Love the Teams presense Chrome extension. Hoping it can get an update...

**Comment by iamacarpet** [comment]
Any reason you think it needs an update?

Worked fine last time I was using it a week or so ago.

**Comment by iamacarpet** [comment]
Ah, sorry, just seen the title of the issue - so it’s stopped working for you?

I’ll look into it tomorrow and see if it’s still working for us.

Do you have any more information about the issues you are experiencing please?

Useful info would be:

- Your operating system 
- Your Chrome version
- Your Teams version (v1 or v2)
- Your Teams URL
- Behaviour experienced, and how are you testing it / observing it?

**Comment by maxweisspoker** [comment]
I apologize for not providing more info. I assumed this would be generally the case for everybody. It has only stopped working in the past few days.  The behavior is that the system is active, but the browser/teams window is not in focus for several minutes, and teams goes from active to away.  Prior to a few days ago, it would simply remain in active (or busy, or whatever) indefinitely while not in focus.  Here's my specs:

OS: Ubuntu 22.04 LTS
Chrome version:  Microsoft Edge 128.0.2739.42
Teams version:  v2
Teams URL:  https://teams.microsoft.com/v2/

I will test again using stock Chrome, and report back.  Sorry again for not providing more info initially.

**Comment by iamacarpet** [comment]
No worries, sorry for not reading the issue properly on the first reply :)

Ok, I've had time to do some checking and it's working for me & others on Chrome OS against Teams v2 (with the same URL as you).

I think it's likely you are seeing a problem with the [Chrome Idle API](https://developer.chrome.com/docs/extensions/reference/api/idle) reporting the system idle/active status properly.

This could be due to it being Edge rather than Chrome, or, it could be something to do with the desktop environment on Linux (I'm not super familiar with modern desktop Linux and what mechanism it uses to track this, as I haven't used it directly in a while)...

This extension itself just reads data from the [Chrome Idle API](https://developer.chrome.com/docs/extensions/reference/api/idle) and if it thinks you are "active", injects "mousemove" events into the Teams tab, which triggers you to stay in the "Available" status.

From my own testing, if the plugin isn't working at all, you'd go "Away"/"Inactive" as soon as the Teams tab loses focus - this is the default Teams Web behaviour, or was last time I checked - so I'd assume the fact you only go "Away"/"Inactive" some time after leaving the tab, hints more at a problem with the Idle API status.

**Comment by maxweisspoker** [comment]
Thanks for that clear information. I will close the ticket now since you've looked into it and determined that the issue is not the extension.  Thanks so much for your help and prompt replies! And thanks for the great work!

As an aside, I was not able to test using stock Chrome, because only Edge works with the SSO login framework I have to use for work.
